#if defined(UNICODEMAP_ENABLE)
#    define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS, UNICODE_MODE_WINCOMPOSE
#endif

#pragma once

#define BLE_INDICATOR_PREFIX
#define BLE_SLOT_1_INDICATOR 1
#define BLE_SLOT_2_INDICATOR 2
#define BLE_SLOT_3_INDICATOR 3

#define BLE_INDICATOR_PREFIX
#define ESB_INDICATOR 5
